package com.ediposouza.teslesgendstracker

/**
 * Created by EdipoSouza on 11/15/16.
 */
val TIME_PATTERN = "HH:mm"
val SEASON_UUID_PATTERN = "yyyy_MM"
val NEWS_UUID_PATTERN = "yyyy_MM_dd"
val NEWS_DATE_PATTERN = "MMMM d, yyyy"

val DEFAULT_DELIMITER = ";"
val TEXT_UNKNOWN = "unknown"
val DECK_NAME_MIN_SIZE = 5

val PREF_USER_DONATE = "ud"
val PREF_NEWS_CHECK_LAST_TIME = "newsCheckPref"

val PPKA = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlL9jJqmVwaD9jJ68bVbu4B61CY1FLSZLMuNU/"
val PPKB = "ncIi3PwpZjFlhKemDBq5szv2ZQVc6hiJwImQHSopf5RdlbgAkV0wLWg1ExIN5UkM9I1vxN5wz1RRvYY/PLzJYsbNR/"
val PPKC = "r96FZiJvSICi3jErbQsg1C/Y68TsZ67TSHuZ6XN2m2HOR0iKoF93kcl7TGKJgoYn8FGmND1j+bgdvkWwu/RQ/EY89XGEP7R3qib78QG5p3gj9rcKYSm8CG76QKDUL/"
val PPKD = "NqD1B1imUJOdBdQ50gRlReqw4c5DTJKWLCzMpzNHb0vDlAwTdgGNsm3i+b5WbnrMHJBpBptQsX8vsKdOghr7DK9zwIDAQAB"